### ISSUE TITLE
Search bar returns all resutls, even if "only" one species is selected in secondary ui

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#34]
If I select "only" one species in the secondary UI, then subsequent searches from the Network Search Bar should be constrained by that selection.

We might also consider exposing the species selector as a "settings" option the Network Search Bar (see Christian's demo tool and stringApp examples). This would need to reciprocally share settings with the secondary UI.

**Comment by AlexanderPico** [comment]
Even after fixing #37, this bug remains.  Steps to reproduce:

1. Use search bar to search for "WP430", hit enter
2. Ignore results and close dialog.
3. Now search for "statin", hit enter 
=> expected: dialog with statin results and "statin" in search field
=> observed: dialog with statin results but with "WP430" in search field

4. Now choose Human only and then close dialog
5. Search for "tp53", hit enter
=> expected: dialog with only human tp53 results and "tp53" in search field
=> observed: dialog with all tp53 results and "WP430" in search field (see screenshot)

<img width="709" alt="screen shot 2017-08-06 at 2 44 22 pm" src="https://user-images.githubusercontent.com/1418193/29007403-86be6986-7ab7-11e7-9555-9e33d8484001.png">

**Comment by AdamStuart** [comment]
fixed

**Comment by AlexanderPico** [comment]
Fields are in sync now (great!), but I'm still seeing a reset of species filtering...

**Comment by AdamStuart** [comment]
this seems to be working now

**Comment by AdamStuart** [comment]
got it
