### ISSUE TITLE
split edge paths

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#42]
To be considered as a special case, I noticed that any edge with an anchor is actually translated into 2 edges into Cytoscape!  This is a nifty trick, but certainly breaks any hope of reusing PathVisio code or waypoints. 

Currently, for example, the lower left transport of Cholesterol out of the Enterocyte was originally a single line. In Cytoscape it is now 2 lines and each line has the SAME pair of original waypoints. This is why those lines looks so crazy.

If we are going to split lines into two segments, we'll have to devise a new way to calculate the waypoints...  MIght be too difficult!  Should we try drawing the original lines without splitting them?

**Comment by AdamStuart** [comment]
Yes, I brought this up yesterday.  
But currently you can move waypoints and NOT nodes, so the fix includes unlocking node position.

**Comment by AlexanderPico** [comment]
Much improved! Now it is really easy to make minor fixes to edges and anchor positions in Cytoscape.

But for WP430, I still an issue for the edge from Lipoprotein to HDL. It's bending is the completely wrong direction. Any guesses?

<img width="424" alt="screen shot 2017-08-06 at 2 49 58 pm" src="https://user-images.githubusercontent.com/1418193/29007380-d30ac5b0-7ab6-11e7-825d-44d90883660a.png">

**Comment by AlexanderPico** [comment]
It's probably time now to test with series of many possible edge paths. See test GPML from Anders...

**Comment by AlexanderPico** [comment]
The issue is with RelX=0.5 (or -0.5) rather than integer....

![test1 gpml](https://user-images.githubusercontent.com/1418193/29145316-7f8c145e-7d11-11e7-9dce-fe9b29ed628a.png)

**Comment by AdamStuart** [comment]
fixed but needs more testing

**Comment by AlexanderPico** [comment]
Just did git pull, built and tested. I still see the issue...

**Comment by AlexanderPico** [comment]
Ah, noted the new app name and tested again... It works with WP430 and other related test files.
